### ISSUE TITLE
HTML highlighting breaks and text goes green when more than 5 anchor elements in a p element

### ISSUE THREAD

**Issue by deanedridge** [atom/language-html#206] opened 2018-07-26 08:56 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

HTML highlighting breaks and text goes green when more than 5 anchor elements in a p element

### Steps to Reproduce

1. Grab the markup from this file:
https://test.dean.kiwi/editors/atom/syntax-highlighting-bug-demo.html

And paste it into the Atom editor

2. Notice the highlighting fails and all turns green when a "&gt;" is encountered in the last anchor element in the paragraph.

**Expected behavior:** It should be highlighted like the markup earlier on in the file.

**Actual behavior:** Highlighting goes green for all characters after encountering the "&gt;" within the last anchor element in the paragraph.

**Reproduces how often:** It does it all the time.

### Versions

1.28.1 x64 and 1.29.0-beta2 on MacOS 10.13.5
I couldn't get apm version as I have both release and beta version installed so not sure how to access apm version when using two versions.

This document validates as valid HTML.

Having 6 anchor elements in this paragraph causes this bug, but having only 5 anchor elements does not. Doesn't matter which anchor element you remove, as long as it reduces down to 5 anchor elements the bug goes away.

Also, if I remove the id attribute (id="interested-in") from the paragraph element, the bug goes away

Here's a screen shot:
<img width="906" alt="screen shot 2018-07-26 at 20 05 19" src="https://user-images.githubusercontent.com/2125708/43251232-eadd3f74-90ae-11e8-9ea4-71ff1ae460e2.png">

**Comment by rsese** [comment] 2018-07-31 04:13
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/atom/issues/1667 so you can subscribe there if you'd like.   As mentioned in https://github.com/atom/atom/issues/1667#issuecomment-383244855, this is fixed in tree-sitter now for supported languages (you can confirm if you enable tree-sitter in `Settings > Core > Use Tree Sitter Parsers`).

Here's what I see with tree-sitter enabled:

![tree-sitter-html](https://github-slack.s3.amazonaws.com/monosnap/untitled__githubatom_2018-07-26_17-52-21.png)

About this:

> I couldn't get apm version as I have both release and beta version installed so not sure how to access apm version when using two versions.

`apm -v` will report for the stable release and `apm-beta -v` will report for beta.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-07-31 04:13 UTC

**Comment by deanedridge** [comment] 2018-07-31 08:28
Yes, I can confirm: the error is not present when tree-sitter is enabled.
