### ISSUE TITLE
Syntax Theme Highlighting completely breaks after line feeds inside attribute values

### ISSUE THREAD

**Issue by exse2** [atom/language-html#198] opened 2018-05-02 15:14 UTC
This does not depend on any specific Syntax Theme, but in this example, "One Light" was used.

Reproduce:

Create new file test.html with following 4 lines in it:

`<!doctype html><html><head></head><body>`
`<div style="margin:0 auto;`
`color: rgba(255,255,255,0.5);">`
`<i class="fa fa-folder-o"></i></div></body></html>`

Right bottom, Atom shows "HTML" as grammar.
Note the Line-Feed (aka simply hit return key on keyboard) after `auto;`. 
From `<i>` onwards, **syntax highlighting is broken and displays only two colors**. It is not coloring the elements in the same color before that point.
If you delete the Line-Feed, everything is working as intended.

**Comment by rsese** [comment] 2018-05-02 19:35
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/language-html/issues/194 so you can subscribe there for updates if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2018-05-02 19:35 UTC
