### ISSUE TITLE
tag match wrong

### ISSUE THREAD

**Issue by yubaoquan** [atom/language-html#182] opened 2017-12-20 13:10 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The html tag will match wrong if newline is in a opening tag part

### Steps to Reproduce

1. write html tags below
2. click each div

```html
<div>
    <div>
        <div class="a"
        >
        </div>
    </div>
</div>

```

**Expected behavior:** 
Out div match to out div, middle div match middle div, inner div matches inner div

**Actual behavior:** 
Out and middle div match wrong

**Reproduces how often:** 
100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.24.0-beta1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.11
npm  3.10.10
node 6.9.5 x64
atom 1.24.0-beta1
python 3.6.1
git 2.14.3

macOS High Sierra 10.13.2

### Additional Information

![match](https://user-images.githubusercontent.com/2340296/34208595-fc951b6e-e5c9-11e7-9325-7590afdefa55.gif)

**Comment by 50Wliu** [comment] 2017-12-20 17:47
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/bracket-matcher#333. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-12-20 17:47 UTC
