### ISSUE TITLE
Inline JavaScript Highlighting

### ISSUE THREAD

**Issue by LostInBrittany** [atom/language-html#73] opened 2015-06-24 12:09 UTC
I'm trying to use Atom for Polymer development. In Polymer, elements are declared in headerless HTML files, like this: 

```html
<dom-module is="my-element">
  <style>  [...] </style>
  <template> [...] </template>
</dom-module>
<script>
  // element registration
  Polymer({
   is: "my-element",
   properties: { 
      a:42
    } 
    myFunction: function() {
    }
  })
</script>
```

And currents Atom version doesn't highlight the syntax of JavaScript when it is contained within <script></script> tags unless there is a parent element. I.e. to make work the syntax  highlighting in the precedent example I'd need to wrap it in a div element, something I don't want to do.

Any idea of why? Could it be possible to overcome that limitation?

**Comment by section14** [comment] 2015-06-25 15:10
+1

**Comment by tomByrer** [comment] 2015-08-02 22:13
Also in this case, JS not highlighting in several themes (seems GitHub's highlighter doesn't either):
```htm
<html>
  <head>
    <script src="http://jsblocks.com/jsblocks/blocks.js"></script>
    <script>
      blocks.query({
        name: blocks.observable()
      });
    </script>
  </head>
  <body>
    Name: <input placeholder="Enter your name" data-query="val(name)" />
    <h1>Hello, my name is {{name}}!</h1>
  </body>
</html>
```
![atom_htm-syntax-script](https://cloud.githubusercontent.com/assets/1308419/9028279/48fcd02a-3931-11e5-9939-1c952ba650e8.jpg)

**Comment by burodepeper** [comment] 2015-08-18 08:01
@LostInBrittany I think your issue is theme related. The theme I'm currently working on highlights your inline Javascript just fine, see the example below. Could you send me some of your Polymer source code for testing?

![schermafbeelding 2015-08-18 om 09 53 15](https://cloud.githubusercontent.com/assets/3703530/9325038/dee0b0ec-458f-11e5-85b1-1f2741874378.png)

@tomByrer Your inline javascript is actually being parsed. It's more of a case that the parser leaves a lot of the code untouched, and it is therefor rendered in the default text color. I've noticed this myself to, mostly because syntax highlighting in javascript is limited in my opinion.

**Comment by LostInBrittany** [comment] 2015-08-18 08:18
I don't know if it's a theme related issue or not, but it's a weird one.

Here you have a screenshot of a Polymer element declaration with no indentation in the script block:

![image](https://cloud.githubusercontent.com/assets/726476/9325395/436c0a3c-4592-11e5-9858-6a03800f306a.png)

And here the same code with the script block indented:

![image](https://cloud.githubusercontent.com/assets/726476/9325403/5153489a-4592-11e5-9085-5c5413aa042c.png)

Now syntax highlating is working! No idea why...

The code is simple:

```
<link rel="import" href="../../dependencies/polymer/polymer.html">

<dom-module name="empty-element" attributes="">
  <template>
    <div><h1>I'm a template!</h1></div>
  </template>
</dom-module>
<script>
  Polymer("empty-element", {
    is: "my-element",
    properties: {
      a:42
    }
    myFunction: function() {
    }
  });
</script>
```

**Comment by burodepeper** [comment] 2015-08-18 08:23
Could you try it with the theme I'm working on, and see if the problem persists without the extra indentation? [minimal-syntax](https://atom.io/packages/minimal-syntax)

**Comment by LostInBrittany** [comment] 2015-08-18 20:00
I've tried a fresh instance of Atom (no extra packages) and your theme, and
it works...
Weird...

**Comment by burodepeper** [comment] 2015-08-19 07:26
@LostInBrittany What syntax theme did you use? I'm curious what actually caused it...

**Comment by 50Wliu** [comment] 2015-11-12 01:29
I cannot reproduce using any of the three HTML snippets posted above using language-html v0.42.0, and it seems like the issue was resolved anyway, so closing.

**Closed by 50Wliu** 2015-11-12 01:29 UTC
