### ISSUE TITLE
I can't change the Tab Length

### ISSUE THREAD

**Issue by vuki** [atom/language-html#130] opened 2016-08-12 10:28 UTC
I have set global Tab Length in Atom to 4. Now i want to change TL to 2 only for language-html, but it won't let me to do it.

- I'm entering '2' into the Tab Length field
- It changes itself to 'Default: 2' for a moment,
- then it changes back to '4'.

If I leave the field empty, it says 'Default: 2', but the tab stop is still 4.

**Comment by 50Wliu** [comment] 2016-08-12 14:51
This is a duplicate of atom/settings-view#774 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-08-12 14:51 UTC
