### ISSUE TITLE
Embedded CSS Breaks Syntax Highlighting

### ISSUE THREAD

**Issue by EEKimS** [atom/language-html#121] opened 2016-06-20 15:46 UTC
I write a lot of HTML newsletter code, and in order to make these run on multiple browsers, it is necessary to include a large block of css styles in the head of the document.

![css-syntax-issue](https://cloud.githubusercontent.com/assets/7404404/16200533/fd6eb432-36ca-11e6-8ecd-c51159e3ca0d.jpg)

Somewhere in the Style tag the syntax stops working, and everything below it loses it's syntax highlighting. 

This is driving me nuts, if i take out the Style block the highlighting works, but i need it in order to work with my newsletters...

is there some way to edit the syntax to treat everything inside a style block as unstyled text at least?

**Comment by krisatthenet** [comment] 2016-07-11 15:12
I have the same issue, really annoying 
![screen shot 2016-07-11 at 18 11 36](https://cloud.githubusercontent.com/assets/10253200/16735765/f7618de8-4792-11e6-88d3-c86e1e83c872.png)

**Comment by EEKimS** [comment] 2016-09-20 16:00
are there any updates on this? i had to write php plugins to merge the html and css documents, i would really like to be able to use this without losing the syntax highlighting!

**Comment by Tekbr** [comment] 2017-02-16 17:17
Any news on that?

**Comment by EEKimS** [comment] 2017-02-16 17:19
i have had to build a workaround in php, but it's  really poor solution, any chance this is going to get fixed?

**Comment by 50Wliu** [comment] 2017-09-17 11:57
In order to fix this I'll need someone to provide a code snippet that reproduces the error.

**Comment by Tekbr** [comment] 2017-10-09 14:59
-- Sorry for the English, I used Google Translator --

@50Wliu For me just start typing in the `<style></style> ` tag

```
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8" />
  <style media="screen">
    
  </style>
</head>

<body>
      <h5>
           Teste Teste Teste
      </h5>
      <img src="view/teste.png" width="850" height="353" />
      <hr>
      <div class="tab-content">
        <div class="tab-pane active" id="teste">
              <h5>
                  <b> Teste</b>
              </h5>
         </div>
       </div>
</body>

</html>
```
Start typing a `b` between the style tag and you'll see the problem
```
<style media="screen">
    b
</style>

```


//ping @EEKimS , @krisatthenet

**Comment by 50Wliu** [comment] 2017-10-16 11:15
It looks like this is because you have invalid CSS inside the style tag.  Can you provide an example that contains valid CSS and is still incorrectly highlighted?

**Comment by EEKimS** [comment] 2017-10-16 14:06
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
<meta http-equiv="X-UA-Compatible" content="IE=8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>A Title</title>
	
<style type="text/css">
* {	-moz-box-sizing: border-box; -webkit-box-sizing: border-box; -box-sizing: border-box; box-sizing: border-box;}
/* Client-specific Styles */
         #outlook a {padding:0;} /* Force Outlook to provide a "view in browser" menu link. */
         body{width:100%!important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0;}
         /* Prevent Webkit and Windows Mobile platforms from changing default font sizes, while not breaking desktop design. */
         .ExternalClass {width:100%;} /* Force Hotmail to display emails at full width */
         .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;} /* Force Hotmail to display normal line spacing. */
         #backgroundTable {margin:0; padding:0; width:100%!important; line-height: 100%!important;}
         img {outline:none; text-decoration:none;border:none; -ms-interpolation-mode: bicubic;}
         a img {border:none;}
         .image-fix {display:block;}
         p {margin: 0px 0px!important;}
         table td {border-collapse: collapse;}
         table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; }
         a {color: #33b9ff;text-decoration: none;text-decoration:none!important;}
/*IPAD STYLES*/
         @media only screen and (max-width: 640px) {
         a[href^="tel"], a[href^="sms"] {
         text-decoration: none;
         color: #0a8cce; /* or whatever your want */
         pointer-events: none;
         cursor: default;
         }
         .mobile-link a[href^="tel"], .mobile-link a[href^="sms"] {
         text-decoration: default;
         color: #0a8cce!important;
         pointer-events: auto;
         cursor: default;
         }
/* Re-style iPhone auto links */
        .applelinks a {
    color:#222222;
    text-decoration: none;
}
/* Hotmail symbol fix*/
.ExternalClass img[class^=Emoji] {
width: 10px!important;
height: 10px!important;
display: inline!important;
}
/*****
FLUID
*****/
table[class=fullWidth] {width: 100%!important; max-width: 600px!important;}
table[class=contentWrap] {width: 100%!important; max-width: 580px!important;}
table[class=thirds] {width: 100%!important; max-width: 172px!important;}
table[class=halves] {width: 100%!important; max-width: 275px!important;}
table[class=innerhalves] {width: 100%!important; max-width: 272px!important;}

@media only screen and (max-width: 600px) {
  img[class=fullImg] {width: 100%!important; height: auto!important; margin: 0 auto;}
  table[class=contentWrap], 
  table[class=button],
  table[class=thirds], 
  table[class=halves],
  table[class=innerhalves],
  table[class=thirdsBlock]  {width: 100%!important; max-width: 100%!important;}
  table[class=thirds] td {text-align: center!important;}
  table[class=thirds] td[class=offerImg] {border-top: 2px solid #3399cc; background: #a3cce0!important; padding: 10px 0;!important}
}
</style>
</head>
<body>

<table width="100%" cellpadding="0" cellspacing="0" border="0" align="left"><tbody><tr>
<td bgcolor="#ffffff" width="600" class="fullWidth" style="font-size: 10px; line-height 10px;">

	<table class="fullWidth" width="600" cellpadding="0" cellspacing="0" border="0" align="center"><tbody><tr><td align="center" bgcolor="#304e88" style="vertical-align: top;">
```

as soon as you start adding anything after the css, there is no syntax highlighting.

**Comment by 50Wliu** [comment] 2017-10-16 15:29
Thanks, that helps.  It looks like you're missing a closing bracket for the `@media` declaration on line 26 (iPad styles).

It looks like this only happens when there's invalid CSS.  While I would love to be able to tokenize HTML correctly even if the CSS is incorrect, that is currently blocked on atom/first-mate#83.

**Closed by 50Wliu** 2017-10-16 15:29 UTC
Labels: bug, more-information-needed

**Comment by EEKimS** [comment] 2017-10-16 15:36
Damn, you're right, that bracket must have been missing for a long time... thanks for spotting that!
That does still leave me with a question though, is there a limit  on the number of characters that can be in the style tag before it loses formatting? (some of these newsletters can get really heavy on the CSS)

**Comment by 50Wliu** [comment] 2017-10-16 15:43
There shouldn't be a limit to the number of _lines_ in a style tag.  Just be aware that Atom stops tokenizing if a certain line is too long.

**Comment by EEKimS** [comment] 2017-10-16 15:45
okay, thank you, it is kind of nice to know that when that happens it means i messed something up in the CSS
Thanks for looking into this :)

**Comment by Tekbr** [comment] 2017-10-16 16:15
-- Sorry for the English, I used Google Translator --

@50Wliu Sorry for the silly question.

But being invalid or incomplete does not mean that it should interfere with the rest of the document. The same should be restricted in the `<style> </ style>` tag.

Just like with `scritp` tag no?

**Comment by EEKimS** [comment] 2017-10-16 16:26
You are doing very will with translator, i understand you just fine :)
Email templates are very sensitive, sometimes one missing bracket can break an email layout really badly.
I only meant that the next time my document loses the syntax highlighting, it means i missed something in my CSS code. So i am fine now, knowing it was my error that broke it.

**Comment by Tekbr** [comment] 2017-10-16 17:46
@50Wliu Ohh, my fault. 😆  I had not checked without closing `{`. 😊 


@EEKimS The Google translation was bad for this! It made no sense to me! 😕 😞 

> You are doing very will with translator, i understand you just fine :)

**Comment by bigsee** [comment] 2018-04-24 12:08
@Tekbr sorry to intrude but maybe Google Translate was confusing you because the quote contains a tiny typo. It should read:

> You are doing very _well_ with translator, i understand you just fine :)

Hope that helps - and agree that you did a great job with Translate! 😀

**Comment by Tekbr** [comment] 2018-04-25 20:14
-- Sorry for the English, I used Google Translator --

@bigsee Thanks for the correction!! 😄
