### ISSUE TITLE
'html' does not provide entire snippet

### ISSUE THREAD

**Issue by chhudson** [atom/language-html#72] opened 2015-06-16 04:04 UTC
Whenever I simply type 'html' (without singlequotes) it does not include the doctype or charset additions. 

Tried reinstalling to no avail...help me -___-

**Comment by izuzak** [comment] 2015-06-17 12:07
@chhudson Can you please provide [more information](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#submitting-issues) and follow the [debugging docs](https://atom.io/docs/latest/hacking-atom-debugging)? Can you reproduce the problem in [safe mode](https://atom.io/docs/latest/hacking-atom-debugging#check-if-the-problem-shows-up-in-safe-mode)?

**Comment by 50Wliu** [comment] 2015-11-01 20:17
@chhudson For now I'm going to close this issue since it works for me and no additional info was provided.  Feel free to comment here though with the answers to @izuzak's questions :).

**Closed by 50Wliu** 2015-11-01 20:17 UTC
Labels: more-information-needed
