### ISSUE TITLE
Toggle Comments places cursor outside of comment block

### ISSUE THREAD

**Issue by mnquintana** [atom/language-html#65] opened 2015-05-18 19:32 UTC
![untitled](https://cloud.githubusercontent.com/assets/823545/7688504/e5c6f386-fd72-11e4-855d-5c232a63b87f.gif)

Currently, the Toggle Comments command places the cursor outside of the comment block – not sure if this is a regression or not.

Atom 0.199.0
OS X 10.10.3

**Comment by 50Wliu** [comment] 2015-11-01 20:16
Closing as a duplicate of atom/atom#4784.

**Closed by 50Wliu** 2015-11-01 20:16 UTC
Labels: bug
