### ISSUE TITLE
Is it possible to have inline css autocomplete in html “style” tags?

### ISSUE THREAD

**Issue by musayazlik** [atom/language-html#232] opened 2019-08-17 07:56 UTC
Will there be such a feature in the Atom editor? 

![Screenshot_2](https://user-images.githubusercontent.com/33998073/63208501-97499c80-c0dd-11e9-924c-5ab05dcdcd88.jpg)

**Comment by rsese** [comment] 2019-08-19 17:06
Thanks for contributing!

We noticed that this looks like a duplicate of https://github.com/atom/autocomplete-css/issues/113 so you can subscribe there if you'd like.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2019-08-19 17:06 UTC
