### ISSUE TITLE
HTML snippets simply not working when I press tab

### ISSUE THREAD

**Issue by rs86** [atom/language-html#61] opened 2015-05-11 20:00 UTC
For some reason HTML snippets stopped working. I am using node 0.198.0 and language-html 0.37.0.

When I press Alt+Shift+S, it only shows the snippet for legal and lorem ipsum.

But for any other language, snippets work fine.

Sorry I can't provide how to reproduce it, but I have no idea why it happens.

I delete atom.app and installed it again, then it worked again. Two days later, it stopped worked once more.

Any ideas?

Thanks

**Comment by lee-dohm** [comment] 2015-05-12 02:00
Can you reproduce the issue if you completely close all instances of Atom and start Atom again using `atom --safe`?

**Comment by rs86** [comment] 2015-05-12 03:44
Yes. I tried it with --safe and it still didn't work.

I removed ~/.atom and reinstalled Atom.app. Apparently this fixed my
problem.

On Monday, May 11, 2015, Lee Dohm <notifications@github.com> wrote:

> Can you reproduce the issue if you completely close all instances of Atom
> and start Atom again using atom --safe?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atom/language-html/issues/61#issuecomment-101097829>.
>


-- 
Rodrigo Stevaux
Monashees Capital
rstevaux@monashees.com.br
+55 11  5501 2018
+55 11 96609 2645

**Comment by lee-dohm** [comment] 2015-05-12 04:19
Can this be closed then? Please let us know if this issue reoccurs or if you have more information.

**Comment by Pixlblitz** [comment] 2015-05-12 09:49
Hi, I have the same issue. I found out that if your HTML file is empty, only the "legal" and "lorem ipsum" snippets are available. If one writes an opening and closing tag <> all snippets become available. This is quite annoying as one has to delete these tags afterwards. Making the "doctype" snippet available from the start could be helpful.

**Comment by rs86** [comment] 2015-05-12 12:08
I could reproduce the bug just as @Pixlblitz described. After adding any HTML tag to an empty file, the snippets become available. I think they should always be available - sometimes the user will be writing a partial, for example.

**Comment by izuzak** [comment] 2015-05-12 12:52
@benogle Any chance https://github.com/atom/language-html/pull/56 affected this behavior unintentionally? I believe it was previously possible to open a new tab, flip it to HTML in the grammar selector, type in `html`, press `tab` and the `html` snippet would trigger. Currently, that's not possible.

**Comment by lee-dohm** [comment] 2015-05-12 13:29
I suspect that it was this change that did it:

https://github.com/atom/language-html/commit/bc7c4c9ffcb19d9de77fef670179c8ac4ae5cd52

When you open a new HTML file, the scope is just `.text.html.basic`, which doesn't match the selector `.html.scope.outside-tag, .html.scope.between-tag-pair`.

**Comment by benogle** [comment] 2015-05-12 16:46
The state of this is that currently, it will work after a tag. So

```html
<!--Does not work here!-->
<span <!--Does not work here-->>
<!--Does work here-->
</span>
<!--Does work here-->
```

The goal was to scope them to only work when the cursor is not in a tag. If they are available in a tag, autocomplete is very noisy in tags with the snippets, and they are 100% never what you want. 

The issue is something in the parser hangs in certain situations with certain regexes in the html grammar (empty matches with lookaheads), so I have removed support for the outside tag scope before a tag in the file. It's something i'd like to fix, but at this point it's a matter of digging into the parser to understand the hang.

Short answer: Have a tag at the top of the page for now (doctype? Parent open tag?).

**Closed** 2015-05-27 18:22 UTC
Labels: bug
