### ISSUE TITLE
Some snippets aren't moving correctly on Tab press

### ISSUE THREAD

**Issue by JFFI** [atom/language-html#195] opened 2018-04-13 22:39 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Some snippets like `label` and `option` are generating this code (I had not seen the `[object Object]` part before this issue happened):
`<label for="[object Object]"></label>`

![selection_006](https://user-images.githubusercontent.com/12106834/38760455-94d27f94-3f38-11e8-8748-193ebbaad26c.png)

And when pressing Tab, instead of moving inside the `for` attribute they jump inside the label tag directly.

![selection_005](https://user-images.githubusercontent.com/12106834/38760470-ac030206-3f38-11e8-8505-9b0af6698a34.png)

### Steps to Reproduce

1. Create a new HTML file
2. Trigger the label snippet
3. Press tab once.

**Expected behavior:** 
The cursor should move inside the value of the `for` attribute.

**Actual behavior:** 
The cursor skips the `for` attribute completely and moves to the tag inner HTML.

**Reproduces how often:** 
100%

### Versions
Atom    : 1.25.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0

apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.25.0
python 2.7.12
git 2.7.4

Ubuntu 16.04

**Comment by rsese** [comment] 2018-04-16 22:19
Thanks for the report!  This is a duplicate of https://github.com/atom/snippets/issues/266 and has been fixed in https://github.com/atom/snippets/pull/267.  The fix is currently available as of `1.26.0-beta2`.

**Closed by rsese** 2018-04-16 22:19 UTC
