### ISSUE TITLE
Syntax highlight broken if text contains ampersand

### ISSUE THREAD

**Issue by seinecle** [atom/language-html#185] opened 2017-12-27 13:49 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Broken highlighter of html after ampersand.

### Steps to Reproduce

1. Write

`<li>How to use the Q&A forum on <a href="https://github.com" target="_blank">Github</a> to get help on the course</li>
`
**Expected behavior:** Correct highlighting

**Actual behavior:** Highltighting breaks after the &

**Reproduces how often:** Always

### Versions

1.23.1 x64

### Additional Information

I have seen this issue open and closed several times here. Still happens to me today.

**Comment by rsese** [comment] 2017-12-28 06:12
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-html/issues/181 and should be fixed in a future release /cc https://github.com/atom/language-html/pull/183.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-28 06:12 UTC
